### ISSUE TITLE
LostCities is a requirement, not a support

### ISSUE THREAD

**Issue by zellfrey** [MCUmbrella/ATG-Modified#1]
```
Missing Mods:
	lostcities : need any]: have missing

net.minecraftforge.fml.common.MissingModsException: Mod atg (Alternate Terrain Generation) requires [lostcities]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:266)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:572)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:334)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:166)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598)
	at java.lang.Thread.run(Thread.java:748)
```

ATG version: atg-1.12.2-2.4.0.jar

LostCities version: lostcities-1.12-2.0.22.jar

Forge: 1.12.2-14.23.5.2846

**Comment by MCUmbrella** [comment]
Due to lack of experience, LostCities is now only available as a  hard dependency of this version of ATG. If you are willing to fix the problem please submit a pull request. Thank for your support!

**Comment by zellfrey** [comment]
You are good my man. I've only just gotten the confidence to do modding and java in general. And looking at ATG it looks far more complicated than a voting mod. I could possibly have a look but I doubt I will get anywhere.

Just as a side note, this isn't a serious issue but maybe just incorrect wording on what the mod supports. It wasn't a trouble setting it up, it just took me by surprise

**Comment by MCUmbrella** [comment]
Solved! Visit https://github.com/MCUmbrella/ATG-Modified/releases/tag/2.5 to download newer version which fixed that.
